name: Docker Build, Push, and Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string
      branch:
        description: 'Branch to build'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            testing/welcome:latest
            testing/welcome:${{ github.event.inputs.tag }}

#  deploy-to-vm:
#    runs-on: ubuntu-latest
#    needs: build-and-push
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

#      - name: Add SSH key
#        uses: webfactory/ssh-agent@v0.7.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#      - name: Deploy to VM
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
#            docker pull testing/welcome:${{ github.event.inputs.tag }} &&
#            docker stop welcome-app || true &&
#            docker rm welcome-app || true &&
#            docker run -d -p 8000:5000 --name welcome-app testing/welcome:${{ github.event.inputs.tag }}
#          "

